### ISSUE TITLE
404: Not Found

### ISSUE THREAD

**Issue by yufuhong** [mustafaozhan/CosmeticScan#4]
Hello there, 'Database.json'  The data source was not found, please answer

**Comment by mustafaozhan** [comment]
Hello @yufuhong ,

Sorry We had to remove the Database.json because of copyright issues

If you wanna test the app, please create a gist and create your database your own, If you wonder the how would be the format of Json file
```
[
    {
      "id": 1,
      "name": "Name 1",
      "information": "Information 1",
      "category": "Category 1",
      "rating": "Good"
    },
    {
      "id": 2,
      "name": "Name 2",
      "information": "Information 2",
      "category": "Category 2",
      "rating": "Bad"
    },
  .
  .
  .
  .
  .
]
```

where `name` is name of ingredient, `information` is short description for ingredient , `category` is category of ingredient and lastly `rating` is how the ingredient effect to human health
That's all I can help you for now 😞
